export const categories = [
  { id: 'all', name: '全部', color: '#60a5fa' },
  { id: 'docs', name: '官方文档', color: '#34d399' },
  { id: 'framework', name: '前端框架', color: '#f472b6' },
  { id: 'ui', name: 'UI组件库', color: '#fbbf24' },
  { id: 'tools', name: '开发工具', color: '#a78bfa' },
  { id: 'learning', name: '学习平台', color: '#f87171' },
  { id: 'resources', name: '资源素材', color: '#22d3ee' },
  { id: 'community', name: '技术社区', color: '#fb923c' },
  { id: 'backend', name: '后端技术', color: '#a3e635' },
  { id: 'devops', name: 'DevOps', color: '#e879f9' },
];

export const websites = [
  // 官方文档 (15个)
  {
    id: '1',
    name: 'MDN Web Docs',
    url: 'https://developer.mozilla.org/zh-CN/',
    description: 'Mozilla 开发者网络，最权威的 Web 技术文档，包含 HTML、CSS、JavaScript 等完整参考',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '2',
    name: 'React 官方文档',
    url: 'https://react.dev/',
    description: 'React 官方文档，学习 React 框架的最佳资源，包含 Hooks、组件等完整指南',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '3',
    name: 'Vue.js 官方文档',
    url: 'https://vuejs.org/',
    description: 'Vue.js 渐进式 JavaScript 框架官方文档，易学易用，性能出色',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '4',
    name: 'Angular 官方文档',
    url: 'https://angular.io/',
    description: 'Google 开发的 Angular 框架官方文档，适合构建大型企业级应用',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '5',
    name: 'TypeScript 文档',
    url: 'https://www.typescriptlang.org/docs/',
    description: 'TypeScript 官方文档，JavaScript 的超集，提供类型系统支持',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '6',
    name: 'Node.js 文档',
    url: 'https://nodejs.org/docs/latest/api/',
    description: 'Node.js 官方 API 文档，服务端 JavaScript 运行环境完整参考',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '7',
    name: 'Next.js 文档',
    url: 'https://nextjs.org/docs',
    description: 'Next.js React 框架文档，支持 SSR、SSG、API 路由等功能',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '8',
    name: 'Nuxt 文档',
    url: 'https://nuxt.com/docs',
    description: 'Nuxt.js 官方文档，基于 Vue 的直观 Web 框架',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '9',
    name: 'Svelte 文档',
    url: 'https://svelte.dev/docs',
    description: 'Svelte 官方文档，编译时框架，无虚拟 DOM，性能优异',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '10',
    name: 'Tailwind CSS 文档',
    url: 'https://tailwindcss.com/docs',
    description: 'Tailwind CSS 实用优先的 CSS 框架文档',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '11',
    name: 'Vite 文档',
    url: 'https://vitejs.dev/guide/',
    description: 'Vite 下一代前端构建工具文档，极速的开发体验',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '12',
    name: 'Webpack 文档',
    url: 'https://webpack.js.org/concepts/',
    description: 'Webpack 模块打包器官方文档',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '13',
    name: 'ES6 入门教程',
    url: 'https://es6.ruanyifeng.com/',
    description: '阮一峰 ES6 标准入门教程，全面介绍 ECMAScript 6 新特性',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '14',
    name: 'GraphQL 文档',
    url: 'https://graphql.org/learn/',
    description: 'GraphQL 查询语言官方文档，API 查询的革命性方式',
    category: 'docs',
    createdAt: Date.now(),
  },
  {
    id: '15',
    name: 'Docker 文档',
    url: 'https://docs.docker.com/',
    description: 'Docker 容器化平台官方文档',
    category: 'docs',
    createdAt: Date.now(),
  },

  // 前端框架 (12个)
  {
    id: '16',
    name: 'React',
    url: 'https://react.dev/',
    description: 'Facebook 开发的用于构建用户界面的 JavaScript 库',
    category: 'framework',
    createdAt: Date.now(),
  },
  {
    id: '17',
    name: 'Vue.js',
    url: 'https://vuejs.org/',
    description: '渐进式 JavaScript 框架，易学易用，性能出色',
    category: 'framework',
    createdAt: Date.now(),
  },
  {
    id: '18',
    name: 'Angular',
    url: 'https://angular.io/',
    description: 'Google 开发的平台，用于构建移动和桌面 Web 应用',
    category: 'framework',
    createdAt: Date.now(),
  },
  {
    id: '19',
    name: 'Svelte',
    url: 'https://svelte.dev/',
    description: '控制论增强的 Web 应用，编译时框架',
    category: 'framework',
    createdAt: Date.now(),
  },
  {
    id: '20',
    name: 'SolidJS',
    url: 'https://www.solidjs.com/',
    description: '简单高效的响应式 JavaScript 库，性能极佳',
    category: 'framework',
    createdAt: Date.now(),
  },
  {
    id: '21',
    name: 'Preact',
    url: 'https://preactjs.com/',
    description: 'React 的轻量级替代方案，仅 3KB',
    category: 'framework',
    createdAt: Date.now(),
  },
  {
    id: '22',
    name: 'Alpine.js',
    url: 'https://alpinejs.dev/',
    description: '类似 Tailwind 的 JavaScript 框架，用于 HTML 行为',
    category: 'framework',
    createdAt: Date.now(),
  },
  {
    id: '23',
    name: 'Lit',
    url: 'https://lit.dev/',
    description: 'Google 开发的简单快速的 Web Components',
    category: 'framework',
    createdAt: Date.now(),
  },
  {
    id: '24',
    name: 'Qwik',
    url: 'https://qwik.builder.io/',
    description: '可恢复性的 Web 框架，即时加载应用',
    category: 'framework',
    createdAt: Date.now(),
  },
  {
    id: '25',
    name: 'Astro',
    url: 'https://astro.build/',
    description: '内容驱动的极速网站构建工具',
    category: 'framework',
    createdAt: Date.now(),
  },
  {
    id: '26',
    name: 'Remix',
    url: 'https://remix.run/',
    description: '专注于 Web 标准的现代 React 框架',
    category: 'framework',
    createdAt: Date.now(),
  },
  {
    id: '27',
    name: 'Gatsby',
    url: 'https://www.gatsbyjs.com/',
    description: '基于 React 的静态站点生成器',
    category: 'framework',
    createdAt: Date.now(),
  },

  // UI 组件库 (12个)
  {
    id: '28',
    name: 'shadcn/ui',
    url: 'https://ui.shadcn.com/',
    description: '设计精美的组件，可复制粘贴到你的应用中',
    category: 'ui',
    createdAt: Date.now(),
  },
  {
    id: '29',
    name: 'Ant Design',
    url: 'https://ant.design/',
    description: '企业级 UI 设计语言和 React 组件库',
    category: 'ui',
    createdAt: Date.now(),
  },
  {
    id: '30',
    name: 'Element Plus',
    url: 'https://element-plus.org/',
    description: '基于 Vue 3 的组件库，适合后台管理系统',
    category: 'ui',
    createdAt: Date.now(),
  },
  {
    id: '31',
    name: 'Material-UI',
    url: 'https://mui.com/',
    description: '基于 Google Material Design 的 React 组件库',
    category: 'ui',
    createdAt: Date.now(),
  },
  {
    id: '32',
    name: 'Chakra UI',
    url: 'https://chakra-ui.com/',
    description: '模块化、可访问的 React 组件库',
    category: 'ui',
    createdAt: Date.now(),
  },
  {
    id: '33',
    name: 'Vuetify',
    url: 'https://vuetifyjs.com/',
    description: '基于 Material Design 的 Vue UI 组件库',
    category: 'ui',
    createdAt: Date.now(),
  },
  {
    id: '34',
    name: 'PrimeVue',
    url: 'https://primevue.org/',
    description: '功能丰富的 Vue UI 组件库',
    category: 'ui',
    createdAt: Date.now(),
  },
  {
    id: '35',
    name: 'Radix UI',
    url: 'https://www.radix-ui.com/',
    description: '无样式、可访问的 React UI 组件原语',
    category: 'ui',
    createdAt: Date.now(),
  },
  {
    id: '36',
    name: 'Headless UI',
    url: 'https://headlessui.com/',
    description: 'Tailwind Labs 开发的无样式 UI 组件',
    category: 'ui',
    createdAt: Date.now(),
  },
  {
    id: '37',
    name: 'DaisyUI',
    url: 'https://daisyui.com/',
    description: 'Tailwind CSS 最受欢迎的组件库',
    category: 'ui',
    createdAt: Date.now(),
  },
  {
    id: '38',
    name: 'Naive UI',
    url: 'https://www.naiveui.com/',
    description: '图森未来开发的 Vue 3 组件库',
    category: 'ui',
    createdAt: Date.now(),
  },
  {
    id: '39',
    name: 'Arco Design',
    url: 'https://arco.design/',
    description: '字节跳动出品的企业级设计系统',
    category: 'ui',
    createdAt: Date.now(),
  },

  // 开发工具 (15个)
  {
    id: '40',
    name: 'VS Code',
    url: 'https://code.visualstudio.com/',
    description: '微软开发的免费开源代码编辑器，最流行的前端 IDE',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '41',
    name: 'CodePen',
    url: 'https://codepen.io/',
    description: '在线代码编辑和展示平台，前端开发者的社交环境',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '42',
    name: 'StackBlitz',
    url: 'https://stackblitz.com/',
    description: '基于浏览器的 IDE，无需安装即可运行 Node.js 环境',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '43',
    name: 'JSFiddle',
    url: 'https://jsfiddle.net/',
    description: '在线测试 JavaScript、CSS、HTML 和 jQuery 代码',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '44',
    name: 'Can I Use',
    url: 'https://caniuse.com/',
    description: '查询 Web 技术在各浏览器的兼容性支持情况',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '45',
    name: 'Postman',
    url: 'https://www.postman.com/',
    description: 'API 开发协作平台，用于构建和测试 API',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '46',
    name: 'Git',
    url: 'https://git-scm.com/',
    description: '分布式版本控制系统，代码管理必备工具',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '47',
    name: 'GitHub',
    url: 'https://github.com/',
    description: '全球最大的代码托管平台和开发者社区',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '48',
    name: 'Figma',
    url: 'https://www.figma.com/',
    description: '基于浏览器的协作界面设计工具',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '49',
    name: 'Vercel',
    url: 'https://vercel.com/',
    description: '前端开发者部署平台，支持 Next.js 等框架',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '50',
    name: 'Netlify',
    url: 'https://www.netlify.com/',
    description: '现代 Web 项目托管和部署平台',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '51',
    name: 'Chrome DevTools',
    url: 'https://developer.chrome.com/docs/devtools/',
    description: 'Chrome 浏览器内置的 Web 开发调试工具',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '52',
    name: 'RegExr',
    url: 'https://regexr.com/',
    description: '在线学习、构建和测试正则表达式',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '53',
    name: 'JSON Crack',
    url: 'https://jsoncrack.com/',
    description: '将 JSON 数据可视化为交互式图表',
    category: 'tools',
    createdAt: Date.now(),
  },
  {
    id: '54',
    name: 'Prettier',
    url: 'https://prettier.io/',
    description: '代码格式化工具，支持多种语言',
    category: 'tools',
    createdAt: Date.now(),
  },

  // 学习平台 (12个)
  {
    id: '55',
    name: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/',
    description: '免费学习编程的非营利性平台，提供完整课程',
    category: 'learning',
    createdAt: Date.now(),
  },
  {
    id: '56',
    name: 'Codecademy',
    url: 'https://www.codecademy.com/',
    description: '互动式编程学习平台，适合初学者入门',
    category: 'learning',
    createdAt: Date.now(),
  },
  {
    id: '57',
    name: 'Udemy',
    url: 'https://www.udemy.com/',
    description: '在线课程平台，有大量前端开发课程',
    category: 'learning',
    createdAt: Date.now(),
  },
  {
    id: '58',
    name: 'Coursera',
    url: 'https://www.coursera.org/',
    description: '顶级大学和公司的在线课程平台',
    category: 'learning',
    createdAt: Date.now(),
  },
  {
    id: '59',
    name: 'Frontend Masters',
    url: 'https://frontendmasters.com/',
    description: '前端进阶培训课程平台，业内专家授课',
    category: 'learning',
    createdAt: Date.now(),
  },
  {
    id: '60',
    name: 'Egghead',
    url: 'https://egghead.io/',
    description: '简短的编程课程平台，适合快速学习',
    category: 'learning',
    createdAt: Date.now(),
  },
  {
    id: '61',
    name: 'Scrimba',
    url: 'https://scrimba.com/',
    description: '互动式视频编程学习平台',
    category: 'learning',
    createdAt: Date.now(),
  },
  {
    id: '62',
    name: 'JavaScript.info',
    url: 'https://javascript.info/',
    description: '现代 JavaScript 教程，从入门到精通',
    category: 'learning',
    createdAt: Date.now(),
  },
  {
    id: '63',
    name: 'CSS-Tricks',
    url: 'https://css-tricks.com/',
    description: 'CSS 技巧和教程网站，前端开发者必读',
    category: 'learning',
    createdAt: Date.now(),
  },
  {
    id: '64',
    name: 'Web.dev',
    url: 'https://web.dev/',
    description: 'Google 提供的现代 Web 开发最佳实践',
    category: 'learning',
    createdAt: Date.now(),
  },
  {
    id: '65',
    name: 'Frontend Roadmap',
    url: 'https://roadmap.sh/frontend',
    description: '前端开发者学习路线图，指引学习方向',
    category: 'learning',
    createdAt: Date.now(),
  },
  {
    id: '66',
    name: 'Fullstack Roadmap',
    url: 'https://roadmap.sh/full-stack',
    description: '全栈开发者学习路线图',
    category: 'learning',
    createdAt: Date.now(),
  },

  // 资源素材 (12个)
  {
    id: '67',
    name: 'Iconfont',
    url: 'https://www.iconfont.cn/',
    description: '阿里巴巴矢量图标库，海量免费图标资源',
    category: 'resources',
    createdAt: Date.now(),
  },
  {
    id: '68',
    name: 'Font Awesome',
    url: 'https://fontawesome.com/',
    description: '最流行的图标字体和 CSS 工具包',
    category: 'resources',
    createdAt: Date.now(),
  },
  {
    id: '69',
    name: 'Heroicons',
    url: 'https://heroicons.com/',
    description: 'Tailwind CSS 官方出品的精美 SVG 图标',
    category: 'resources',
    createdAt: Date.now(),
  },
  {
    id: '70',
    name: 'unDraw',
    url: 'https://undraw.co/',
    description: '开源插图库，可自定义颜色，免费商用',
    category: 'resources',
    createdAt: Date.now(),
  },
  {
    id: '71',
    name: 'Unsplash',
    url: 'https://unsplash.com/',
    description: '高质量免费 stock 照片库',
    category: 'resources',
    createdAt: Date.now(),
  },
  {
    id: '72',
    name: 'Google Fonts',
    url: 'https://fonts.google.com/',
    description: 'Google 提供的免费开源字体库',
    category: 'resources',
    createdAt: Date.now(),
  },
  {
    id: '73',
    name: 'CDNJS',
    url: 'https://cdnjs.com/',
    description: '开源 CDN 服务，托管大量前端库',
    category: 'resources',
    createdAt: Date.now(),
  },
  {
    id: '74',
    name: 'jsDelivr',
    url: 'https://www.jsdelivr.com/',
    description: '免费开源 CDN，加速 npm 和 GitHub 资源',
    category: 'resources',
    createdAt: Date.now(),
  },
  {
    id: '75',
    name: 'Color Hunt',
    url: 'https://colorhunt.co/',
    description: '设计师配色方案分享平台',
    category: 'resources',
    createdAt: Date.now(),
  },
  {
    id: '76',
    name: 'UI Gradients',
    url: 'https://uigradients.com/',
    description: '渐变色配色方案生成工具',
    category: 'resources',
    createdAt: Date.now(),
  },
  {
    id: '77',
    name: 'Dribbble',
    url: 'https://dribbble.com/',
    description: '设计师作品展示平台，获取设计灵感',
    category: 'resources',
    createdAt: Date.now(),
  },
  {
    id: '78',
    name: 'Behance',
    url: 'https://www.behance.net/',
    description: 'Adobe 旗下的创意作品展示平台',
    category: 'resources',
    createdAt: Date.now(),
  },

  // 技术社区 (10个)
  {
    id: '79',
    name: 'Stack Overflow',
    url: 'https://stackoverflow.com/',
    description: '全球最大的开发者问答社区',
    category: 'community',
    createdAt: Date.now(),
  },
  {
    id: '80',
    name: 'Dev.to',
    url: 'https://dev.to/',
    description: '开发者社区和博客平台，分享技术文章',
    category: 'community',
    createdAt: Date.now(),
  },
  {
    id: '81',
    name: 'Hashnode',
    url: 'https://hashnode.com/',
    description: '开发者博客平台，免费自定义域名',
    category: 'community',
    createdAt: Date.now(),
  },
  {
    id: '82',
    name: '掘金',
    url: 'https://juejin.cn/',
    description: '中文技术社区，优质前端技术文章',
    category: 'community',
    createdAt: Date.now(),
  },
  {
    id: '83',
    name: 'SegmentFault',
    url: 'https://segmentfault.com/',
    description: '中文开发者问答社区',
    category: 'community',
    createdAt: Date.now(),
  },
  {
    id: '84',
    name: '知乎',
    url: 'https://www.zhihu.com/',
    description: '中文问答社区，有大量技术讨论',
    category: 'community',
    createdAt: Date.now(),
  },
  {
    id: '85',
    name: 'Reddit - Web Dev',
    url: 'https://www.reddit.com/r/webdev/',
    description: 'Reddit Web 开发版块',
    category: 'community',
    createdAt: Date.now(),
  },
  {
    id: '86',
    name: 'Hacker News',
    url: 'https://news.ycombinator.com/',
    description: 'Y Combinator 的技术新闻社区',
    category: 'community',
    createdAt: Date.now(),
  },
  {
    id: '87',
    name: 'Product Hunt',
    url: 'https://www.producthunt.com/',
    description: '发现最新科技产品和工具',
    category: 'community',
    createdAt: Date.now(),
  },
  {
    id: '88',
    name: 'Indie Hackers',
    url: 'https://www.indiehackers.com/',
    description: '独立开发者社区，分享创业经验',
    category: 'community',
    createdAt: Date.now(),
  },

  // 后端技术 (12个)
  {
    id: '89',
    name: 'Express.js',
    url: 'https://expressjs.com/',
    description: 'Node.js 极简 Web 应用框架',
    category: 'backend',
    createdAt: Date.now(),
  },
  {
    id: '90',
    name: 'NestJS',
    url: 'https://nestjs.com/',
    description: '渐进式 Node.js 框架，支持 TypeScript',
    category: 'backend',
    createdAt: Date.now(),
  },
  {
    id: '91',
    name: 'Fastify',
    url: 'https://www.fastify.io/',
    description: '快速低开销的 Node.js Web 框架',
    category: 'backend',
    createdAt: Date.now(),
  },
  {
    id: '92',
    name: 'Koa',
    url: 'https://koajs.com/',
    description: 'Express 原班人马打造的下一代框架',
    category: 'backend',
    createdAt: Date.now(),
  },
  {
    id: '93',
    name: 'Prisma',
    url: 'https://www.prisma.io/',
    description: '下一代 Node.js 和 TypeScript ORM',
    category: 'backend',
    createdAt: Date.now(),
  },
  {
    id: '94',
    name: 'MongoDB',
    url: 'https://www.mongodb.com/',
    description: '流行的 NoSQL 文档数据库',
    category: 'backend',
    createdAt: Date.now(),
  },
  {
    id: '95',
    name: 'PostgreSQL',
    url: 'https://www.postgresql.org/',
    description: '强大的开源关系型数据库',
    category: 'backend',
    createdAt: Date.now(),
  },
  {
    id: '96',
    name: 'Redis',
    url: 'https://redis.io/',
    description: '内存数据结构存储，用作缓存和消息代理',
    category: 'backend',
    createdAt: Date.now(),
  },
  {
    id: '97',
    name: 'GraphQL',
    url: 'https://graphql.org/',
    description: 'API 查询语言，替代 REST',
    category: 'backend',
    createdAt: Date.now(),
  },
  {
    id: '98',
    name: 'tRPC',
    url: 'https://trpc.io/',
    description: '端到端类型安全的 API',
    category: 'backend',
    createdAt: Date.now(),
  },
  {
    id: '99',
    name: 'Socket.io',
    url: 'https://socket.io/',
    description: '实时双向事件驱动通信库',
    category: 'backend',
    createdAt: Date.now(),
  },
  {
    id: '100',
    name: 'JWT.io',
    url: 'https://jwt.io/',
    description: 'JSON Web Token 官方文档和调试工具',
    category: 'backend',
    createdAt: Date.now(),
  },
];
